<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>OpenSim.Server.Handlers</AssemblyName>
    <Deterministic>true</Deterministic>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE</DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>True</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>False</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants></DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>False</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>True</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DotNetOpenId" >
      <Name>DotNetOpenId</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\DotNetOpenId.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="log4net" >
      <Name>log4net</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mono.Addins" >
      <Name>Mono.Addins</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Mono.Addins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini" >
      <Name>Nini</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse" >
      <Name>OpenMetaverse</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse.StructuredData" >
      <Name>OpenMetaverse.StructuredData</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.StructuredData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes" >
      <Name>OpenMetaverseTypes</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="XMLRPC" >
      <Name>XMLRPC</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\XMLRPC.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\OpenSim.Framework.csproj" />
    <ProjectReference Include="..\..\Framework\Console\OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="..\..\Framework\Servers\HttpServer\OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="..\Base\OpenSim.Server.Base.csproj" />
    <ProjectReference Include="..\..\Services\Base\OpenSim.Services.Base.csproj" />
    <ProjectReference Include="..\..\Services\Interfaces\OpenSim.Services.Interfaces.csproj" />
    <ProjectReference Include="..\..\Services\UserAccountService\OpenSim.Services.UserAccountService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AgentPreferences\AgentPreferencesServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="AgentPreferences\AgentPreferencesServiceConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetServerDeleteHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetServerGetHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetsExistHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authentication\AuthenticationServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authentication\AuthenticationServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authentication\OpenIdServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authentication\OpenIdServerHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authorization\AuthorizationServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Authorization\AuthorizationServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\AvatarServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\AvatarServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="BakedTextures\XBakes.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="BakedTextures\XBakesHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Base\ServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Base\Utils.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Estate\EstateDataRobustConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Freeswitch\FreeswitchServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Friends\FriendServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Friends\FriendsServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Grid\GridInfoHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Grid\GridInfoServerInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Grid\GridServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Grid\GridServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="GridUser\GridUserServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="GridUser\GridUserServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\AgentHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\GatekeeperServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\HeloServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\HGFriendServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\HGFriendsServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\HomeAgentHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\HypergridHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\InstantMessageServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Hypergrid\UserAgentServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Inventory\InventoryServerInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Inventory\InventoryServerMoveItemsHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Inventory\XInventoryInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Land\LandHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Land\LandServiceInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Login\LLLoginHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Login\LLLoginServiceInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Map\MapAddServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Map\MapGetServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Map\MapRemoveServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="MuteList\MuteListServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="MuteList\MuteListServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Neighbour\NeighbourHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Neighbour\NeighbourServiceInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Presence\PresenceServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Presence\PresenceServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Profiles\UserProfilesConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Profiles\UserProfilesHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Simulation\AgentHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Simulation\ObjectHandlers.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Simulation\SimulationServiceInConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Simulation\Utils.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserAccounts\UserAccountServerConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserAccounts\UserAccountServerPostHandler.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
