<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>OpenSim.Region.OptionalModules</AssemblyName>
    <Deterministic>true</Deterministic>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE</DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>True</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>False</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants></DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>False</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>True</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Ionic.Zip" >
      <Name>Ionic.Zip</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Ionic.Zip.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="log4net" >
      <Name>log4net</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mono.Addins" >
      <Name>Mono.Addins</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Mono.Addins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mono.Data.SqliteClient" >
      <Name>Mono.Data.SqliteClient</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Mono.Data.SqliteClient.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NDesk.Options" >
      <Name>NDesk.Options</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\NDesk.Options.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netcd" >
      <Name>netcd</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\netcd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini" >
      <Name>Nini</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse" >
      <Name>OpenMetaverse</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse.StructuredData" >
      <Name>OpenMetaverse.StructuredData</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.StructuredData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes" >
      <Name>OpenMetaverseTypes</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Drawing.Common" >
      <Name>System.Drawing.Common</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\System.Drawing.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="XMLRPC" >
      <Name>XMLRPC</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\XMLRPC.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Capabilities\OpenSim.Capabilities.csproj" />
    <ProjectReference Include="..\..\Data\OpenSim.Data.csproj" />
    <ProjectReference Include="..\..\Framework\OpenSim.Framework.csproj" />
    <ProjectReference Include="..\..\Framework\Console\OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="..\..\Framework\Monitoring\OpenSim.Framework.Monitoring.csproj" />
    <ProjectReference Include="..\..\Framework\Servers\OpenSim.Framework.Servers.csproj" />
    <ProjectReference Include="..\..\Framework\Servers\HttpServer\OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="..\ClientStack\Linden\UDP\OpenSim.Region.ClientStack.LindenUDP.csproj" />
    <ProjectReference Include="..\CoreModules\OpenSim.Region.CoreModules.csproj" />
    <ProjectReference Include="..\Framework\OpenSim.Region.Framework.csproj" />
    <ProjectReference Include="..\PhysicsModules\SharedBase\OpenSim.Region.PhysicsModules.SharedBase.csproj" />
    <ProjectReference Include="..\..\Server\Base\OpenSim.Server.Base.csproj" />
    <ProjectReference Include="..\..\Server\Handlers\OpenSim.Server.Handlers.csproj" />
    <ProjectReference Include="..\..\Services\Base\OpenSim.Services.Base.csproj" />
    <ProjectReference Include="..\..\Services\Connectors\OpenSim.Services.Connectors.csproj" />
    <ProjectReference Include="..\..\Services\Interfaces\OpenSim.Services.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Agent\InternetRelayClientView\IRCStackModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Agent\InternetRelayClientView\Server\IRCClientView.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Agent\InternetRelayClientView\Server\IRCServer.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Agent\TextureSender\J2KDecoderCommandModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Agent\UDP\Linden\LindenUDPInfoModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Asset\AssetInfoModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Animations\AnimationsCommandModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Appearance\AppearanceInfoModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Chat\ChannelState.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Chat\IRCBridgeModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Chat\IRCConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Chat\RegionState.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Concierge\ConciergeModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Friends\FriendsCommandsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\SitStand\SitStandCommandsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Voice\FreeSwitchVoice\FreeSwitchVoiceModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\Voice\VivoxVoice\VivoxVoiceModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\XmlRpcGroups\GroupsMessagingModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\XmlRpcGroups\GroupsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\XmlRpcGroups\IGroupsServicesConnector.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Avatar\XmlRpcGroups\XmlRpcGroupsServicesConnectorModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\DataRequestHandler.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\DataSnapshotManager.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\EstateSnapshot.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\LandSnapshot.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\LLSDDiscovery.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\ObjectSnapshot.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\SnapshotStore.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\Interfaces\IDataSnapshot.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="DataSnapshot\Interfaces\IDataSnapshotProvider.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Example\BareBonesNonShared\BareBonesNonSharedModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Example\BareBonesShared\BareBonesSharedModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Example\WebSocketEchoTest\WebSocketEchoModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Framework\Monitoring\EtcdMonitoringModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Materials\MaterialsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="PhysicsParameters\PhysicsParameters.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="PrimLimitsModule\PrimLimitsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Scripting\RegionReadyModule\RegionReadyModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ServiceConnectorsIn\Freeswitch\FreeswitchServiceInConnectorModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\ActiveConnectionsAJAX.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\Clients_report.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\Default_Report.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\HTMLUtil.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\IStatsReport.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\LogLinesAJAX.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\Prototype_distributor.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\Sessions_Report.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\SimStatsAJAX.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\Updater_distributor.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="UserStatistics\WebStatsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\CameraOnlyModeModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\DynamicFloaterModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\DynamicMenuModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\GodNamesModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\SimulatorFeaturesHelper.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="ViewerSupport\SpecialUIModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\AutoBackup\AutoBackupModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\AutoBackup\AutoBackupModuleState.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\MoneyModule\SampleMoneyModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\NPC\NPCAvatar.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\NPC\NPCModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\SceneCommands\SceneCommandsModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\TreePopulator\TreePopulatorModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\WorldView\WorldViewModule.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="World\WorldView\WorldViewRequestHandler.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
