<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>OpenSim.ConsoleClient</AssemblyName>
    <Deterministic>true</Deterministic>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants>TRACE</DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>True</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>False</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile>
    </ConfigurationOverrideFile>
    <DefineConstants></DefineConstants>
    <DocumentationFile></DocumentationFile>
    <DebugSymbols>False</DebugSymbols>
    <FileAlignment>4096</FileAlignment>
    <Optimize>True</Optimize>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <UseCommonOutputDirectory>True</UseCommonOutputDirectory>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>False</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\bin\</OutputPath>
    <RegisterForComInterop>False</RegisterForComInterop>
    <RemoveIntegerChecks>False</RemoveIntegerChecks>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>False</NoStdLib>
    <NoWarn>CA1416,SYSLIB0011,SYSLIB0014,SYSLIB0039</NoWarn>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net" >
      <Name>log4net</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Nini" >
      <Name>Nini</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\Nini.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse" >
      <Name>OpenMetaverse</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverse.StructuredData" >
      <Name>OpenMetaverse.StructuredData</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverse.StructuredData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OpenMetaverseTypes" >
      <Name>OpenMetaverseTypes</Name>
      <HintPath>D:\My_Work\academic\practice\eden\bin\OpenMetaverseTypes.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework\OpenSim.Framework.csproj" />
    <ProjectReference Include="..\Framework\Console\OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="..\Framework\Servers\OpenSim.Framework.Servers.csproj" />
    <ProjectReference Include="..\Framework\Servers\HttpServer\OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="..\Server\Base\OpenSim.Server.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ConsoleClient.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Requester.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
